CRM.Web/Models/Entities/DealProduct.cs
namespace CRM.Web.Models.Entities
{
    public class DealProduct : BaseEntity
    { 
        public int DealId { get; set; }
        public Deal Deal { get; set; }
        public int ProductId { get; set; }
        public Product Product { get; set; }
        public int Quantity { get; set; }
    }
}

CRM.Web/Controllers/DealProductsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CRM.Web.Models.Entities;
using CRM.Web.Data;
using CRM.Web.Services;

namespace CRM.Web.Controllers
{
    public class DealProductsController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IDealProductsService _dealsProductsServices;

        public DealProductsController(AppDbContext context, IDealProductsService dealProductsService)
        {
            _context = context;
            _dealsProductsServices = dealProductsService;
        }

        // GET: DealProducts
        public async Task<IActionResult> Index()
        {
            var dealsItems = await _dealsProductsServices.GetAll();
            
            return View(dealsItems);
        }

        // GET: DealProducts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dealProduct = await _dealsProductsServices.GetById(id);
            
            if (dealProduct == null)
            {
                return NotFound();
            }

            return View(dealProduct);
        }

        // GET: DealProducts/Create
        public IActionResult Create()
        {
            ViewData["DealId"] = new SelectList(_context.Deals, "Id", "Name");
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Name");
            
            return View();
        }

        // POST: DealProducts/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DealId,ProductId,Id,CreatedDate,UpdatedDate,Quantity")] DealProduct dealProduct)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index");
            }

            var successful = await _dealsProductsServices.Create(dealProduct);

            if (!successful)
            {
                return BadRequest("Could not add Deal Item.");
            }

            ViewData["DealId"] = new SelectList(_context.Deals, "Id", "Name", dealProduct.DealId);
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Name", dealProduct.ProductId);

            return RedirectToAction("Index");
        }

        // GET: DealProducts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dealProduct = await _dealsProductsServices.GetById(id);
            
            if (dealProduct == null)
            {
                return NotFound();
            }
            
            ViewData["DealId"] = new SelectList(_context.Deals, "Id", "Name", dealProduct.DealId);
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Name", dealProduct.ProductId);
            
            return View(dealProduct);
        }

        // POST: DealProducts/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DealId,ProductId,Id,CreatedDate,UpdatedDate,Quantity")] DealProduct dealProduct)
        {
            if (id != dealProduct.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var result = await _dealsProductsServices.Update(dealProduct);

                    if (result == false)
                    {
                        return NotFound();
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!(await _dealsProductsServices.Exists(dealProduct.Id)))
                    {
                        return NotFound();
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            ViewData["DealId"] = new SelectList(_context.Deals, "Id", "Name", dealProduct.DealId);
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Name", dealProduct.ProductId);
            
            return View(dealProduct);
        }

        // GET: DealProducts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dealProduct = await _dealsProductsServices.GetById(id);

            if (dealProduct == null)
            {
                return NotFound();
            }

            return View(dealProduct);
        }

        // POST: DealProducts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var result = await _dealsProductsServices.Delete(id);

            if (result == false)
            {
                return NotFound();
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

CRM.Web/Controllers/DealsController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CRM.Web.Models.Entities;
using CRM.Web.Models.ViewModels;
using CRM.Web.Services;
using CRM.Web.Data;

namespace CRM.Web.Controllers
{
    public class DealsController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IDealsService _dealsService;

        public DealsController(AppDbContext context, IDealsService dealsService)
        {
            _context = context;
            _dealsService = dealsService;
        }

        // GET: Deals
        public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter, int? pageNumber)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["TotalAmountSortParm"] = sortOrder == "TotalAmount" ? "total_amount_desc" : "TotalAmount";
            ViewData["StageSortParm"] = sortOrder == "Stage" ? "stage_desc" : "Stage";
            ViewData["ContactSortParm"] = sortOrder == "Contact" ? "contact_desc" : "Contact";
            ViewData["CompanySortParm"] = sortOrder == "Company" ? "company_desc" : "Company";
            ViewData["SalesmanSortParm"] = sortOrder == "Salesman" ? "salesman_desc" : "Salesman";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            var deals = await _dealsService.GetPaginatedList(sortOrder, searchString, currentFilter, pageNumber);

            return View(deals);
        }

        // GET: Deals/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return View("NotFound");
            }

            var deal = await _dealsService.GetById(id);

            if (deal == null)
            {
                return View("NotFound");
            }

            List<DealProduct> dealProducts = new List<DealProduct>();
            List<Product> products = new List<Product>();

            dealProducts = deal.DealsProducts;

            foreach (DealProduct dealProduct in deal.DealsProducts)
            {
                products.Add(dealProduct.Product);
            }

            DetailsDealViewModel dealViewModel = new DetailsDealViewModel
            {
                Deal = deal,
                Company = deal.Company,
                Contact = deal.Contact,
                Salesman = deal.Salesman,
                DealProducts = dealProducts,
                Products = products
            };

            return View(dealViewModel);
        }

        // GET: Deals/Create
        public IActionResult Create()
        {
            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Name");
            ViewData["ContactId"] = new SelectList(_context.Contacts, "Id", "Email");
            ViewData["SalesmanId"] = new SelectList(_context.Salesmen, "Id", "Email");

            return View();
        }

        // POST: Deals/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,TotalAmount,Stage,Description,ClosingDate,ContactId,CompanyId,SalesmanId,Id,CreatedDate,UpdatedDate")] FormDealViewModel dealViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View("NotFound");
            }

            Deal deal = new Deal 
            {
                Name = dealViewModel.Name,
                TotalAmount = dealViewModel.TotalAmount,
                Stage = (Deal.DealStage)dealViewModel.Stage,
                Description = dealViewModel.Description,
                ClosingDate = dealViewModel.ClosingDate,
                ContactId = dealViewModel.ContactId,
                CompanyId = dealViewModel.CompanyId,
                SalesmanId = dealViewModel.SalesmanId
            };

            var successful = await _dealsService.Create(deal);

            if (!successful)
            {
                return View("NotFound");
            }

            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Name", deal.CompanyId);
            ViewData["ContactId"] = new SelectList(_context.Contacts, "Id", "Email", deal.ContactId);
            ViewData["SalesmanId"] = new SelectList(_context.Salesmen, "Id", "Email", deal.SalesmanId);
            
            return RedirectToAction(nameof(Index));
        }

        // GET: Deals/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return View("NotFound");
            }

            var deal = await _dealsService.GetById(id);

            if (deal == null)
            {
                return View("NotFound");
            }
            
            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Name", deal.CompanyId);
            ViewData["ContactId"] = new SelectList(_context.Contacts, "Id", "Email", deal.ContactId);
            ViewData["SalesmanId"] = new SelectList(_context.Salesmen, "Id", "Email", deal.SalesmanId);

            FormDealViewModel dealViewModel = new FormDealViewModel
            {
                Id = deal.Id,
                Name = deal.Name,
                TotalAmount = deal.TotalAmount,
                Stage = (FormDealViewModel.DealStage)deal.Stage,
                Description = deal.Description,
                ClosingDate = deal.ClosingDate,
                ContactId = deal.ContactId,
                CompanyId = deal.CompanyId,
                SalesmanId = deal.SalesmanId,
                CreatedDate = deal.CreatedDate,
                UpdatedDate = deal.UpdatedDate
            };

            return View(dealViewModel);
        }

        // POST: Deals/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,TotalAmount,Stage,Description,ClosingDate,ContactId,CompanyId,SalesmanId,Id,CreatedDate,UpdatedDate")] FormDealViewModel dealViewModel)
        {
            if (id != dealViewModel.Id)
            {
                return View("NotFound");
            }

            Deal deal = new Deal
            {
                Id = dealViewModel.Id,
                Name = dealViewModel.Name,
                TotalAmount = dealViewModel.TotalAmount,
                Stage = (Deal.DealStage)dealViewModel.Stage,
                Description = dealViewModel.Description,
                ClosingDate = dealViewModel.ClosingDate,
                ContactId = dealViewModel.ContactId,
                CompanyId = dealViewModel.CompanyId,
                SalesmanId = dealViewModel.SalesmanId,
                CreatedDate = dealViewModel.CreatedDate,
                UpdatedDate = dealViewModel.UpdatedDate
            };

            if (ModelState.IsValid)
            {
                try
                {
                    var result = await _dealsService.Update(deal);
                    
                    if (result == false)
                    {
                        return View("NotFound");
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!(await _dealsService.Exists(deal.Id)))
                    {
                        return View("NotFound");
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Name", deal.CompanyId);
            ViewData["ContactId"] = new SelectList(_context.Contacts, "Id", "Email", deal.ContactId);
            ViewData["SalesmanId"] = new SelectList(_context.Salesmen, "Id", "Email", deal.SalesmanId);
            
            return View(dealViewModel);
        }

        // GET: Deals/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return View("NotFound");
            }

            var deal = await _dealsService.GetById(id);

            if (deal == null)
            {
                return View("NotFound");
            }

            return View(deal);
        }

        // POST: Deals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            if (id == null)
            {
                return View("NotFound");
            }

            var result = await _dealsService.Delete(id);

            if (result == false)
            {
                return View("NotFound");
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> GenerateSalesQuote(int id)
        {
            var file = await _dealsService.CreateQuotePDF(id);

            return File(file, "application/pdf", "Quote.pdf");
        }
    }
}

CRM.Web/Views/DealProducts/Create.cshtml
@model DealProduct

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Create new Deal Item</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DealId" class="control-label">Deal</label>
                <select asp-for="DealId" class="form-control" asp-items="ViewBag.DealId">
                    <option selected="selected" value="">--Please select---</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="ProductId" class="control-label">Product</label>
                <select asp-for="ProductId" class="form-control" asp-items="ViewBag.ProductId">
                    <option selected="selected" value="">--Please select---</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="CreatedDate" class="control-label">Created Date</label>
                <input asp-for="CreatedDate" class="form-control" />
                <span asp-validation-for="CreatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UpdatedDate" class="control-label">Updated Date</label>
                <input asp-for="UpdatedDate" class="form-control" />
                <span asp-validation-for="UpdatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label">Quantity</label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CRM.Web/Views/DealProducts/Delete.cshtml
@model DealProduct

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Are you sure you want to delete this Deal Item?</h3>
<div>
    <hr />
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Yes (Delete)" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-success">No (Cancel)</a>
    </form>
</div>

CRM.Web/Views/DealProducts/Details.cshtml
@model DealProduct

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <div class="button-panel">
        <h3>Deal Item</h3>
        <p>
            <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary btn-sm">Edit</a>
        </p>
        <p>
            <a asp-action="Create" class="btn btn-primary btn-sm">Create</a>
        </p>
        <p>
            <a asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-primary btn-sm">Delete</a>
        </p>
    </div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Deal
        </dt>
        <dd class="col-sm-10">
            <a asp-controller="Deals" asp-action="Details" asp-route-id="@Model.DealId">
                @Html.DisplayFor(model => model.Deal.Name)
            </a>
        </dd>
        <dt class="col-sm-2">
            Product
        </dt>
        <dd class="col-sm-10">
            <a asp-controller="Products" asp-action="Details" asp-route-id="@Model.ProductId">
                @Html.DisplayFor(model => model.Product.Name)
            </a>
        </dd>
        <dt class="col-sm-2">
            Created Date
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class="col-sm-2">
            Quantity
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class="col-sm-2">
            Updated Date
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>
    </dl>
</div>

CRM.Web/Views/DealProducts/Edit.cshtml
@model DealProduct

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Edit Deal Item</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DealId" class="control-label">Deal</label>
                <select asp-for="DealId" class="form-control" asp-items="ViewBag.DealId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ProductId" class="control-label">Product</label>
                <select asp-for="ProductId" class="form-control" asp-items="ViewBag.ProductId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedDate" class="control-label">Created Date</label>
                <input asp-for="CreatedDate" class="form-control" />
                <span asp-validation-for="CreatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UpdatedDate" class="control-label">Updated Date</label>
                <input asp-for="UpdatedDate" class="form-control" />
                <span asp-validation-for="UpdatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CRM.Web/Views/DealProducts/Index.cshtml
@model IEnumerable<DealProduct>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table class="table">
    <thead>
        <tr>
            <th>
                Deal
            </th>
            <th>
                Product
            </th>
            <th>
                Created Date
            </th>
            <th>
                Updated Date
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr onclick="location.href = '@(Url.Action("Details", "DealProducts", new { id = item.Id }))'">
                <td>
                    @Html.DisplayFor(modelItem => item.Deal.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UpdatedDate)
                </td>
                <td>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-default">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>