CRM.Web/Controllers/DealsController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CRM.Web.Models.Entities;
using CRM.Web.Models.ViewModels;
using CRM.Web.Services;
using CRM.Web.Data;

namespace CRM.Web.Controllers
{
    public class DealsController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IDealsService _dealsService;

        public DealsController(AppDbContext context, IDealsService dealsService)
        {
            _context = context;
            _dealsService = dealsService;
        }

        // GET: Deals
        public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter, int? pageNumber)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["TotalAmountSortParm"] = sortOrder == "TotalAmount" ? "total_amount_desc" : "TotalAmount";
            ViewData["StageSortParm"] = sortOrder == "Stage" ? "stage_desc" : "Stage";
            ViewData["ContactSortParm"] = sortOrder == "Contact" ? "contact_desc" : "Contact";
            ViewData["CompanySortParm"] = sortOrder == "Company" ? "company_desc" : "Company";
            ViewData["SalesmanSortParm"] = sortOrder == "Salesman" ? "salesman_desc" : "Salesman";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            var deals = await _dealsService.GetPaginatedList(sortOrder, searchString, currentFilter, pageNumber);

            return View(deals);
        }

        // GET: Deals/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return View("NotFound");
            }

            var deal = await _dealsService.GetById(id);

            if (deal == null)
            {
                return View("NotFound");
            }

            List<DealProduct> dealProducts = new List<DealProduct>();
            List<Product> products = new List<Product>();

            dealProducts = deal.DealsProducts;

            foreach (DealProduct dealProduct in deal.DealsProducts)
            {
                products.Add(dealProduct.Product);
            }

            DetailsDealViewModel dealViewModel = new DetailsDealViewModel
            {
                Deal = deal,
                Company = deal.Company,
                Contact = deal.Contact,
                Salesman = deal.Salesman,
                DealProducts = dealProducts,
                Products = products
            };

            return View(dealViewModel);
        }

        // GET: Deals/Create
        public IActionResult Create()
        {
            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Name");
            ViewData["ContactId"] = new SelectList(_context.Contacts, "Id", "Email");
            ViewData["SalesmanId"] = new SelectList(_context.Salesmen, "Id", "Email");

            return View();
        }

        // POST: Deals/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,TotalAmount,Stage,Description,ClosingDate,ContactId,CompanyId,SalesmanId,Id,CreatedDate,UpdatedDate")] FormDealViewModel dealViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View("NotFound");
            }

            Deal deal = new Deal 
            {
                Name = dealViewModel.Name,
                TotalAmount = dealViewModel.TotalAmount,
                Stage = (Deal.DealStage)dealViewModel.Stage,
                Description = dealViewModel.Description,
                ClosingDate = dealViewModel.ClosingDate,
                ContactId = dealViewModel.ContactId,
                CompanyId = dealViewModel.CompanyId,
                SalesmanId = dealViewModel.SalesmanId
            };

            var successful = await _dealsService.Create(deal);

            if (!successful)
            {
                return View("NotFound");
            }

            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Name", deal.CompanyId);
            ViewData["ContactId"] = new SelectList(_context.Contacts, "Id", "Email", deal.ContactId);
            ViewData["SalesmanId"] = new SelectList(_context.Salesmen, "Id", "Email", deal.SalesmanId);
            
            return RedirectToAction(nameof(Index));
        }

        // GET: Deals/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return View("NotFound");
            }

            var deal = await _dealsService.GetById(id);

            if (deal == null)
            {
                return View("NotFound");
            }
            
            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Name", deal.CompanyId);
            ViewData["ContactId"] = new SelectList(_context.Contacts, "Id", "Email", deal.ContactId);
            ViewData["SalesmanId"] = new SelectList(_context.Salesmen, "Id", "Email", deal.SalesmanId);

            FormDealViewModel dealViewModel = new FormDealViewModel
            {
                Id = deal.Id,
                Name = deal.Name,
                TotalAmount = deal.TotalAmount,
                Stage = (FormDealViewModel.DealStage)deal.Stage,
                Description = deal.Description,
                ClosingDate = deal.ClosingDate,
                ContactId = deal.ContactId,
                CompanyId = deal.CompanyId,
                SalesmanId = deal.SalesmanId,
                CreatedDate = deal.CreatedDate,
                UpdatedDate = deal.UpdatedDate
            };

            return View(dealViewModel);
        }

        // POST: Deals/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,TotalAmount,Stage,Description,ClosingDate,ContactId,CompanyId,SalesmanId,Id,CreatedDate,UpdatedDate")] FormDealViewModel dealViewModel)
        {
            if (id != dealViewModel.Id)
            {
                return View("NotFound");
            }

            Deal deal = new Deal
            {
                Id = dealViewModel.Id,
                Name = dealViewModel.Name,
                TotalAmount = dealViewModel.TotalAmount,
                Stage = (Deal.DealStage)dealViewModel.Stage,
                Description = dealViewModel.Description,
                ClosingDate = dealViewModel.ClosingDate,
                ContactId = dealViewModel.ContactId,
                CompanyId = dealViewModel.CompanyId,
                SalesmanId = dealViewModel.SalesmanId,
                CreatedDate = dealViewModel.CreatedDate,
                UpdatedDate = dealViewModel.UpdatedDate
            };

            if (ModelState.IsValid)
            {
                try
                {
                    var result = await _dealsService.Update(deal);
                    
                    if (result == false)
                    {
                        return View("NotFound");
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!(await _dealsService.Exists(deal.Id)))
                    {
                        return View("NotFound");
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Name", deal.CompanyId);
            ViewData["ContactId"] = new SelectList(_context.Contacts, "Id", "Email", deal.ContactId);
            ViewData["SalesmanId"] = new SelectList(_context.Salesmen, "Id", "Email", deal.SalesmanId);
            
            return View(dealViewModel);
        }

        // GET: Deals/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return View("NotFound");
            }

            var deal = await _dealsService.GetById(id);

            if (deal == null)
            {
                return View("NotFound");
            }

            return View(deal);
        }

        // POST: Deals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            if (id == null)
            {
                return View("NotFound");
            }

            var result = await _dealsService.Delete(id);

            if (result == false)
            {
                return View("NotFound");
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> GenerateSalesQuote(int id)
        {
            var file = await _dealsService.CreateQuotePDF(id);

            return File(file, "application/pdf", "Quote.pdf");
        }
    }
}

CRM.Web/Controllers/SalesmenController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CRM.Web.Models.Entities;
using CRM.Web.Data;
using CRM.Web.Models.ViewModels;
using CRM.Web.Services;

namespace CRM.Web.Controllers
{
    public class SalesmenController : Controller
    {
        private readonly AppDbContext _context;
        private readonly ISalesmenService _salesmanServiece;

        public SalesmenController(AppDbContext context, ISalesmenService salesmenService)
        {
            _context = context;
            _salesmanServiece = salesmenService;
        }

        // GET: Salesmen
        public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter, int? pageNumber)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["FirstNameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "first_name_desc" : "";
            ViewData["LastNameSortParm"] = sortOrder == "LastName" ? "last_name_desc" : "LastName";
            ViewData["PhoneSortParm"] = sortOrder == "Phone" ? "phone_desc" : "Phone";
            ViewData["EmailSortParm"] = sortOrder == "Email" ? "email_desc" : "Email";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            var salesmen = await _salesmanServiece.GetPaginatedList(sortOrder, searchString, currentFilter, pageNumber);

            return View(salesmen);
        }

        // GET: Salesmen/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return View("NotFound");
            }

            var salesman = await _salesmanServiece.GetById(id);

            if (salesman == null)
            {
                return View("NotFound");
            }

            var salesmanViewModel = new DetailsSalesmanViewModel
            {
                Salesman = salesman,
                Activities = salesman.Activities,
                Deals = salesman.Deals
            };

            return View(salesmanViewModel);
        }

        // GET: Salesmen/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Salesmen/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FirstName,LastName,Phone,Email,MonthlySalesGoal,Id,CreatedDate,UpdatedDate")] FormSalesmanViewModel salesmanViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            Salesman salesman = new Salesman 
            {
                FirstName = salesmanViewModel.FirstName,
                LastName = salesmanViewModel.LastName,
                Phone = salesmanViewModel.Phone,
                Email = salesmanViewModel.Email,
                MonthlySalesGoal = salesmanViewModel.MonthlySalesGoal
            };

            var successful = await _salesmanServiece.Create(salesman);

            if (!successful)
            {
                return View("NotFound");
            }

            return RedirectToAction(nameof(Index));
        }

        // GET: Salesmen/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return View("NotFound");
            }

            var salesman = await _salesmanServiece.GetById(id);

            if (salesman == null)
            {
                return View("NotFound");
            }

            FormSalesmanViewModel salesmanViewModel = new FormSalesmanViewModel
            {
                Id = salesman.Id,
                FirstName = salesman.FirstName,
                LastName = salesman.LastName,
                Phone = salesman.Phone,
                Email = salesman.Email,
                MonthlySalesGoal = salesman.MonthlySalesGoal,
                CreatedDate = salesman.CreatedDate,
                UpdatedDate = salesman.UpdatedDate
            };

            return View(salesmanViewModel);
        }

        // POST: Salesmen/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FirstName,LastName,Phone,Email,MonthlySalesGoal,Id,CreatedDate,UpdatedDate")] FormSalesmanViewModel salesmanViewModel)
        {
            if (id != salesmanViewModel.Id)
            {
                return View("NotFound");
            }

            Salesman salesman = new Salesman
            {
                Id = salesmanViewModel.Id,
                FirstName = salesmanViewModel.FirstName,
                LastName = salesmanViewModel.LastName,
                Phone = salesmanViewModel.Phone,
                Email = salesmanViewModel.Email,
                MonthlySalesGoal = salesmanViewModel.MonthlySalesGoal,
                CreatedDate = salesmanViewModel.CreatedDate,
                UpdatedDate = salesmanViewModel.UpdatedDate
            };

            if (ModelState.IsValid)
            {
                try
                {
                    var result = await _salesmanServiece.Update(salesman);

                    if (result == false)
                    {
                        return View("NotFound");
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!(await _salesmanServiece.Exists(salesman.Id)))
                    {
                        return View("NotFound");
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            return View(salesmanViewModel);
        }

        // GET: Salesmen/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return View("NotFound");
            }

            var salesman = await _salesmanServiece.GetById(id);

            if (salesman == null)
            {
                return View("NotFound");
            }

            return View(salesman);
        }

        // POST: Salesmen/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            if (id == null)
            {
                return View("NotFound");
            }

            var result = await _salesmanServiece.Delete(id);

            if (result == false)
            {
                return View("NotFound");
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

CRM.Web/Views/Salesmen/Create.cshtml
@model FormSalesmanViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Создание нового продавца</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label">Имя</label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label">Фамилия</label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label">Номер мобильного телефона</label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label">Email</label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MonthlySalesGoal" class="control-label">Ежемесячная цель продаж</label>
                <input asp-for="MonthlySalesGoal" class="form-control" />
                <span asp-validation-for="MonthlySalesGoal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Создать" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CRM.Web/Views/Salesmen/Delete.cshtml
@model Salesman

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Вы уверены, что хотите удалить  @Html.DisplayFor(model => model.FirstName)  @Html.DisplayFor(model => model.LastName)?</h3>
<div>
    <hr />
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Да (Удалить)" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-success">Нет (Отменить)</a>
    </form>
</div>

CRM.Web/Views/Salesmen/Details.cshtml
@model DetailsSalesmanViewModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <div class="button-panel">
        <h3>@Html.DisplayFor(model => model.Salesman.FirstName) @Html.DisplayFor(model => model.Salesman.LastName)</h3>
        <p>
            <a asp-action="Edit" asp-route-id="@Model.Salesman.Id" class="btn btn-primary btn-sm">Редактировать</a>
        </p>
        <p>
            <a asp-action="Create" class="btn btn-primary btn-sm">Создать</a>
        </p>
        <p>
            <a asp-action="Delete" asp-route-id="@Model.Salesman.Id" class="btn btn-primary btn-sm">Удалить</a>
        </p>
    </div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Имя
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Salesman.FirstName)
        </dd>
        <dt class="col-sm-2">
            Фамилия
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Salesman.LastName)
        </dd>
        <dt class="col-sm-2">
            Номер мобильного телефона
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Salesman.Phone)
        </dd>
        <dt class="col-sm-2">
            Email
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Salesman.Email)
        </dd>
        <dt class="col-sm-2">
            Ежемесячная цель продаж
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Salesman.MonthlySalesGoal)
        </dd>
        <dt class="col-sm-2">
            Дата регистрации
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Salesman.CreatedDate)
        </dd>
        <dt class="col-sm-2">
            Дата обновления
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Salesman.UpdatedDate)
        </dd>
    </dl>
</div>
<div>
    <h4>Сопутствующая деятельность</h4>
    <div>
        <p>
            <a asp-controller="Activities" asp-action="Create" class="btn btn-primary btn-sm">Добавить</a>
        </p>
    </div>
    <hr />
    <table class="table">
        <thead>
            <tr>
                <th>
                    <a>Название</a>
                </th>
                <th>
                    <a>Род деятельности</a>
                </th>
                <th>
                    <a>Дата начала</a>
                </th>
                <th>
                    <a>Дата окончания</a>
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Activities)
            {
                <tr onclick="location.href = '@(Url.Action("Details", "Activities", new { id = item.Id }))'">
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Type)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.StartDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EndDate)
                    </td>
                    <td>
                        <a asp-controller="Activities" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-default">Редактировать</a> |
                        <a asp-controller="Activities" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-default">Удалить</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div>
    <h4>Сопутствующие сделки</h4>
    <div>
        <p>
            <a asp-controller="Deals" asp-action="Create" class="btn btn-primary btn-sm">Добавить</a>
        </p>
    </div>
    <hr />
    <table class="table">
        <thead>
            <tr>
                <th>
                    <a>Название</a>
                </th>
                <th>
                    <a>Стадия</a>
                </th>
                <th>
                    <a>Общая сумма</a>
                </th>
                <th>
                    <a>Дата совершения</a>
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Deals)
            {
                <tr onclick="location.href = '@(Url.Action("Details", "Deals", new { id = item.Id }))'">
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Stage)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TotalAmount)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ClosingDate)
                    </td>
                    <td>
                        <a asp-controller="Deals" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-default">Edit</a> |
                        <a asp-controller="Deals" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-default">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

CRM.Web/Views/Salesmen/Edit.cshtml
@model FormSalesmanViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Редактирование данных</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label">Имя</label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label">Фамилия</label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label">Номер мобильного телефона</label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label">Email</label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MonthlySalesGoal" class="control-label">Ежемесячная цель продаж</label>
                <input asp-for="MonthlySalesGoal" class="form-control" />
                <span asp-validation-for="MonthlySalesGoal" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="CreatedDate" />
            <input type="hidden" asp-for="UpdatedDate" />
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CRM.Web/Views/Salesmen/Index.cshtml
@model PaginatedList<Salesman>

@{
    Layout = "~/Views/Shared/_ListViewLayout.cshtml";
}

<table class="table">
    <thead>
        <tr>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["FirstNameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Имя</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["LastNameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Фамилия</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["PhoneSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Номер мобильного телефона</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["EmailSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Emial</a>
            </th>
            <th>Действия</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr onclick="location.href = '@(Url.Action("Details", "Salesmen", new { id = item.Id }))'">
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Phone)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-default">Удалить</a>
                </td>
            </tr>
        }
    </tbody>
</table>