CRM.Web/Models/Entities/Activity.cs
using System;

namespace CRM.Web.Models.Entities
{
    public class Activity : BaseEntity
    {
        public string Name { get; set; }

        public string Description { get; set; }
        
        public DateTime StartDate { get; set; }

        public DateTime EndDate { get; set; }
        
        public enum ActivityType
        {
            Call,
            Meeting,
            Task
        }

        public ActivityType Type { get; set; }

        public virtual Contact Contact { get; set; }

        public virtual int ContactId { get; set; }

        public virtual Salesman Salesman { get; set; }

        public virtual int SalesmanId { get; set; }
    }
}

CRM.Web/Controllers/ActivitiesController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CRM.Web.Models.Entities;
using CRM.Web.Data;
using CRM.Web.Services;
using CRM.Web.Models.ViewModels;

namespace CRM.Web.Controllers
{
    public class ActivitiesController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IActivitiesService _activitiesService;

        public ActivitiesController(AppDbContext context, IActivitiesService activitiesService)
        {
            _context = context;
            _activitiesService = activitiesService;
        }

        // GET: Activities
        public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter, int? pageNumber)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["TypeSortParm"] = sortOrder == "Type" ? "type_desc" : "Type";
            ViewData["StartDateSortParm"] = sortOrder == "StartDate" ? "start_date_desc" : "StartDate";
            ViewData["EndDateSortParm"] = sortOrder == "EndDate" ? "end_date_desc" : "EndDate";
            ViewData["ContactSortParm"] = sortOrder == "Contact" ? "contact_desc" : "Contact";
            ViewData["SalesmanSortParm"] = sortOrder == "Salesman" ? "salesman_desc" : "Salesman";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            var activities = await _activitiesService.GetPaginatedList(sortOrder, searchString, currentFilter, pageNumber);

            return View(activities);
        }

        // GET: Activities/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return View("NotFound");
            }

            var activity = await _activitiesService.GetById(id);

            if (activity == null)
            {
                return View("NotFound");
            }

            return View(activity);
        }

        // GET: Activities/Create
        public IActionResult Create()
        {
            ViewData["ContactId"] = new SelectList(_context.Contacts, "Id", "Email");
            ViewData["SalesmanId"] = new SelectList(_context.Salesmen, "Id", "Email");
            
            return View();
        }

        // POST: Activities/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Description,StartDate,EndDate,Type,ContactId,SalesmanId,Id,CreatedDate,UpdatedDate")] FormActivityViewModel activityViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            Activity activity = new Activity
            {
                Name = activityViewModel.Name,
                Description = activityViewModel.Description,
                Type = (Activity.ActivityType)activityViewModel.Type,
                StartDate = activityViewModel.StartDate,
                EndDate = activityViewModel.EndDate,
                ContactId = activityViewModel.ContactId,
                SalesmanId = activityViewModel.SalesmanId
            };

            var successful = await _activitiesService.Create(activity);

            if (!successful)
            {
                return View("NotFound");
            }

            ViewData["ContactId"] = new SelectList(_context.Contacts, "Id", "Email", activity.ContactId);
            ViewData["SalesmanId"] = new SelectList(_context.Salesmen, "Id", "Email", activity.SalesmanId);

            return RedirectToAction(nameof(Index));
        }

        // GET: Activities/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return View("NotFound");
            }

            var activity = await _activitiesService.GetById(id);

            if (activity == null)
            {
                return View("NotFound");
            }
            
            ViewData["ContactId"] = new SelectList(_context.Contacts, "Id", "Email", activity.ContactId);
            ViewData["SalesmanId"] = new SelectList(_context.Salesmen, "Id", "Email", activity.SalesmanId);

            FormActivityViewModel activityViewModel = new FormActivityViewModel 
            {
                Id = activity.Id,
                Name = activity.Name,
                Description = activity.Description,
                Type = (FormActivityViewModel.ActivityType)activity.Type,
                StartDate = activity.StartDate,
                EndDate = activity.EndDate,
                ContactId = activity.ContactId,
                SalesmanId = activity.SalesmanId,
                CreatedDate = activity.CreatedDate,
                UpdatedDate = activity.UpdatedDate
            };

            return View(activityViewModel);
        }

        // POST: Activities/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,Description,StartDate,EndDate,Type,ContactId,SalesmanId,Id,CreatedDate,UpdatedDate")] FormActivityViewModel activityViewModel)
        {
            if (id != activityViewModel.Id)
            {
                return View("NotFound");
            }

            Activity activity = new Activity
            {
                Id = activityViewModel.Id,
                Name = activityViewModel.Name,
                Description = activityViewModel.Description,
                Type = (Activity.ActivityType)activityViewModel.Type,
                StartDate = activityViewModel.StartDate,
                EndDate = activityViewModel.EndDate,
                ContactId = activityViewModel.ContactId,
                SalesmanId = activityViewModel.SalesmanId,
                CreatedDate = activityViewModel.CreatedDate,
                UpdatedDate = activityViewModel.UpdatedDate
            };

            if (ModelState.IsValid)
            {
                try
                {
                    var result = await _activitiesService.Update(activity);

                    if (result == false)
                    {
                        return View("NotFound");
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!(await _activitiesService.Exists(activity.Id)))
                    {
                        return View("NotFound");
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            ViewData["ContactId"] = new SelectList(_context.Contacts, "Id", "Email", activity.ContactId);
            ViewData["SalesmanId"] = new SelectList(_context.Salesmen, "Id", "Email", activity.SalesmanId);
            
            return View(activityViewModel);
        }

        // GET: Activities/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return View("NotFound");
            }

            var activity = await _activitiesService.GetById(id);

            if (activity == null)
            {
                return View("NotFound");
            }

            return View(activity);
        }

        // POST: Activities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            if (id == null)
            {
                return View("NotFound");
            }

            var result = await _activitiesService.Delete(id);

            if (result == false)
            {
                return View("NotFound");
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

CRM.Web/Controllers/ContactsController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CRM.Web.Models.Entities;
using CRM.Web.Models.ViewModels;
using CRM.Web.Services;
using CRM.Web.Data;

namespace CRM.Web.Controllers
{
    public class ContactsController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IContactsService _contactsService;

        public ContactsController(AppDbContext context, IContactsService contactsService)
        {
            _context = context;
            _contactsService = contactsService;
        }

        // GET: Contacts
        public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter, int? pageNumber)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["FirstNameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "first_name_desc" : "";
            ViewData["LastNameSortParm"] = sortOrder == "LastName" ? "last_name_desc" : "LastName";
            ViewData["PhoneSortParm"] = sortOrder == "Phone" ? "phone_desc" : "Phone";
            ViewData["EmailSortParm"] = sortOrder == "Email" ? "email_desc" : "Email";
            ViewData["CompanySortParm"] = sortOrder == "Company" ? "company_desc" : "Company";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            var contacts = await _contactsService.GetPaginatedList(sortOrder, searchString, currentFilter, pageNumber);

            return View(contacts);
        }

        // GET: Contacts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return View("NotFound");
            }

            var contact = await _contactsService.GetById(id);

            if (contact == null)
            {
                return View("NotFound");
            }

            var contactViewModel = new DetailsContactViewModel
            {
                Activities = contact.Activities,
                Company = contact.Company,
                Contact = contact
            };

            return View(contactViewModel);
        }

        // GET: Contacts/Create
        public IActionResult Create()
        {
            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Name");

            return View();
        }

        // POST: Contacts/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FirstName,LastName,Position,Description,Source,Phone,Email,CompanyId,Id,CreatedDate,UpdatedDate")] FormContactViewModel contactViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            Contact contact = new Contact 
            {
                FirstName = contactViewModel.FirstName,
                LastName = contactViewModel.LastName,
                Position = contactViewModel.Position,
                Description = contactViewModel.Description,
                Source = (Contact.Sources)contactViewModel.Source,
                Phone = contactViewModel.Phone,
                Email = contactViewModel.Email,
                CompanyId = contactViewModel.CompanyId
            };

            var successful = await _contactsService.Create(contact);

            if (!successful)
            {
                return View("NotFound");
            }

            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Name", contact.CompanyId);

            return RedirectToAction(nameof(Index));
        }

        // GET: Contacts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return View("NotFound");
            }

            var contact = await _contactsService.GetById(id);
            
            if (contact == null)
            {
                return View("NotFound");
            }

            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Name", contact.CompanyId);

            FormContactViewModel contactViewModel = new FormContactViewModel
            {
                Id = contact.Id,
                FirstName = contact.FirstName,
                LastName = contact.LastName,
                Position = contact.Position,
                Description = contact.Description,
                Source = (FormContactViewModel.Sources)contact.Source,
                Phone = contact.Phone,
                Email = contact.Email,
                CompanyId = contact.CompanyId,
                CreatedDate = contact.CreatedDate,
                UpdatedDate = contact.UpdatedDate
            };

            return View(contactViewModel);
        }

        // POST: Contacts/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FirstName,LastName,Position,Description,Source,Phone,Email,CompanyId,Id,CreatedDate,UpdatedDate")] FormContactViewModel contactViewModel)
        {
            if (id != contactViewModel.Id)
            {
                return View("NotFound");
            }

            Contact contact = new Contact
            {
                Id = contactViewModel.Id,
                FirstName = contactViewModel.FirstName,
                LastName = contactViewModel.LastName,
                Position = contactViewModel.Position,
                Description = contactViewModel.Description,
                Source = (Contact.Sources)contactViewModel.Source,
                Phone = contactViewModel.Phone,
                Email = contactViewModel.Email,
                CompanyId = contactViewModel.CompanyId,
                CreatedDate = contactViewModel.CreatedDate,
                UpdatedDate = contactViewModel.UpdatedDate
            };

            if (ModelState.IsValid)
            {
                try
                {
                    var result = await _contactsService.Update(contact);

                    if (result == false)
                    {
                        return View("NotFound");
                    }

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!(await _contactsService.Exists(contact.Id)))
                    {
                        return View("NotFound");
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Name", contact.CompanyId);
            
            return View(contactViewModel);
        }

        // GET: Contacts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return View("NotFound");
            }

            var contact = await _contactsService.GetById(id);

            if (contact == null)
            {
                return View("NotFound");
            }

            return View(contact);
        }

        // POST: Contacts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            if (id == null)
            {
                return View("NotFound");
            }

            var result = await _contactsService.Delete(id);

            if (result == false)
            {
                return View("NotFound");
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

CRM.Web/Views/Activities/Create.cshtml
@model FormActivityViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Создать новую активность</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Наименование</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Описание</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label">Дата начала</label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label">Дата окончания</label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label">Род деятельности</label>
                <select asp-for="Type" class="form-control" asp-items="Html.GetEnumSelectList<Activity.ActivityType>()">
                    <option selected="selected" value="">---Выберите, пожалуйста---</option>
                </select>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactId" class="control-label">Контакт</label>
                <select asp-for="ContactId" class="form-control" asp-items="ViewBag.ContactId">
                    <option selected="selected" value="">---Выберите, пожалуйста---</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="SalesmanId" class="control-label">Продавец</label>
                <select asp-for="SalesmanId" class="form-control" asp-items="ViewBag.SalesmanId">
                    <option selected="selected" value="">---Выберите, пожалуйста---</option>
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Создать" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CRM.Web/Views/Activities/Delete.cshtml
@model Activity

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Are you sure you want to delete @Html.DisplayFor(model => model.Name)?</h3>
<div>
    <hr />
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Да (Удалить)" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-success">Нет (Назад)</a>
    </form>
</div>

CRM.Web/Views/Activities/Details.cshtml
@model Activity

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <div class="button-panel">
        <h3>@Html.DisplayFor(model => model.Name)</h3>
        <p>
            <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary btn-sm">Редактировать</a>
        </p>
        <p>
            <a asp-action="Create" class="btn btn-primary btn-sm">Создать</a>
        </p>
        <p>
            <a asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-primary btn-sm">Удалить</a>
        </p>
    </div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Род деятельности
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class="col-sm-2">
            Название
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            Описание
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            Дата начала
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class="col-sm-2">
            Дата окончания
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class="col-sm-2">
            Контакт
        </dt>
        <dd class="col-sm-10">
            <a asp-controller="Contacts" asp-action="Details" asp-route-id="@Model.Contact.Id">
                @Html.DisplayFor(model => model.Contact.FirstName) @Html.DisplayFor(model => model.Contact.LastName)
            </a>
        </dd>
        <dt class="col-sm-2">
            Продавец
        </dt>
        <dd class="col-sm-10">
            <a asp-controller="Salesmen" asp-action="Details" asp-route-id="@Model.Salesman.Id">
                @Html.DisplayFor(model => model.Salesman.FirstName) @Html.DisplayFor(model => model.Salesman.LastName)
            </a>
        </dd>
        <dt class="col-sm-2">
            Дата регистрации 
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class="col-sm-2">
            Дата обновления
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>
    </dl>
</div>

CRM.Web/Views/Activities/Edit.cshtml
@model FormActivityViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Редактировать деятельность</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Название</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Описание</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label">Дата начала</label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label">Дата окончания</label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label">Род деятельности</label>
                <select asp-for="Type" class="form-control" asp-items="Html.GetEnumSelectList<FormActivityViewModel.ActivityType>()">
                </select>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactId" class="control-label">Контакт</label>
                <select asp-for="ContactId" class="form-control" asp-items="ViewBag.ContactId"></select>
                <span asp-validation-for="ContactId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SalesmanId" class="control-label">Продавец</label>
                <select asp-for="SalesmanId" class="form-control" asp-items="ViewBag.SalesmanId"></select>
                <span asp-validation-for="SalesmanId" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="CreatedDate" />
            <input type="hidden" asp-for="UpdatedDate" />
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CRM.Web/Views/Activities/Index.cshtml
@model PaginatedList<Activity>

@{
    Layout = "~/Views/Shared/_ListViewLayout.cshtml";
}

<table class="table">
    <thead>
        <tr>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Наименование</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["TypeSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Род деятельности</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["StartDateSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Дата начала</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["EndDateSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Дата окончания</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["ContactSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Контакт</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["SalesmanSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Продавец</a>
            </th>
            <th>Действия</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr onclick="location.href = '@(Url.Action("Details", "Activities", new { id = item.Id }))'">
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Contact.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Salesman.Email)
                </td>
                <td>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-default">Удалить</a>
                </td>
            </tr>
        }
    </tbody>
</table>