CRM.Web/Models/Entities/Contact.cs
using System.Collections.Generic;

namespace CRM.Web.Models.Entities
{
    public class Contact : BaseEntity
    { 
        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string Phone { get; set; }

        public string Email { get; set; }

        public string Position { get; set; }

        public string Description { get; set; }

        public enum Sources
        {
            Blog,
            Calls,
            Social_Media,
            Marketing,
            Events,
            Referrals,
            Website
        }

        public Sources Source { get; set; }

        public virtual Company Company { get; set; }

        public virtual int CompanyId { get; set; }

        public virtual List<Deal> Deals { get; set; }

        public virtual List<Activity> Activities { get; set; }
    }
}

CRM.Web/Controllers/CompaniesController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CRM.Web.Services;
using CRM.Web.Data;
using CRM.Web.Models.ViewModels;
using CRM.Web.Models.Entities;

namespace CRM.Web.Controllers
{
    public class CompaniesController : Controller
    {
        private readonly AppDbContext _context;
        private readonly ICompaniesService _compmaniesServices;

        public CompaniesController(AppDbContext context, ICompaniesService companiesService)
        {
            _context = context;
            _compmaniesServices = companiesService;
        }

        // GET: Companies
        public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter, int? pageNumber)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["TaxpayerNumberSortParm"] = sortOrder == "TaxpayerNumber" ? "taxpayer_number_desc" : "TaxpayerNumber";
            ViewData["CitySortParm"] = sortOrder == "City" ? "city_desc" : "City";
            ViewData["StreetSortParm"] = sortOrder == "Street" ? "street_desc" : "Street";
            ViewData["ZipCodeSortParm"] = sortOrder == "ZipCode" ? "zip_code_desc" : "ZipCode";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            var companies = await _compmaniesServices.GetPaginatedList(sortOrder, searchString, currentFilter, pageNumber);

            return View(companies);
        }

        // GET: Companies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return View("NotFound");
            }

            var company = await _compmaniesServices.GetById(id);

            if (company == null)
            {
                return View("NotFound");
            }

            var companyViewModel = new DetailsCompanyViewModel
            {
                Company = company,
                Contacts = company.Contacts,
                Deals = company.Deals
            };

            return View(companyViewModel);
        }

        // GET: Companies/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Companies/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TaxpayerNumber,Name,Website,NoOfEmployees,Industry,Country,City,Street,ZipCode,Id,CreatedDate,UpdatedDate,Score")] FormCompanyViewModel companyViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            Company company = new Company
            { 
                TaxpayerNumber = companyViewModel.TaxpayerNumber,
                Name = companyViewModel.Name,
                Website = companyViewModel.Website,
                NoOfEmployees = companyViewModel.NoOfEmployees,
                Industry = (Company.Industries)companyViewModel.Industry,
                Country = companyViewModel.Country,
                City = companyViewModel.City,
                Street = companyViewModel.Street,
                ZipCode = companyViewModel.ZipCode
            };

            var successful = await _compmaniesServices.Create(company);

            if (!successful)
            {
                return View("NotFound");
            }

            return RedirectToAction(nameof(Index));
        }

        // GET: Companies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return View("NotFound");
            }

            var company = await _compmaniesServices.GetById(id);
            
            if (company == null)
            {
                return View("NotFound");
            }

            FormCompanyViewModel companyViewModel = new FormCompanyViewModel
            {
                Id = company.Id,
                TaxpayerNumber = company.TaxpayerNumber,
                Name = company.Name,
                Website = company.Website,
                NoOfEmployees = company.NoOfEmployees,
                Industry = (FormCompanyViewModel.Industries)company.Industry,
                Country = company.Country,
                City = company.City,
                Street = company.Street,
                ZipCode = company.ZipCode,
                Score = company.Score,
                CreatedDate = company.CreatedDate,
                UpdatedDate = company.UpdatedDate
            };

            return View(companyViewModel);
        }

        // POST: Companies/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TaxpayerNumber,Name,Website,NoOfEmployees,Industry,Country,City,Street,ZipCode,Id,CreatedDate,UpdatedDate,Score")] FormCompanyViewModel companyViewModel)
        {
            if (id != companyViewModel.Id)
            {
                return View("NotFound");
            }

            Company company = new Company
            {
                Id = companyViewModel.Id,
                TaxpayerNumber = companyViewModel.TaxpayerNumber,
                Name = companyViewModel.Name,
                Website = companyViewModel.Website,
                NoOfEmployees = companyViewModel.NoOfEmployees,
                Industry = (Company.Industries)companyViewModel.Industry,
                Country = companyViewModel.Country,
                City = companyViewModel.City,
                Street = companyViewModel.Street,
                ZipCode = companyViewModel.ZipCode,
                CreatedDate = companyViewModel.CreatedDate,
                UpdatedDate = companyViewModel.UpdatedDate,
                Score = companyViewModel.Score
            };

            if (ModelState.IsValid)
            {
                try
                {
                    var result = await _compmaniesServices.Update(company);

                    if (result == false)
                    {
                        return View("NotFound");
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!(await _compmaniesServices.Exists(company.Id)))
                    {
                        return View("NotFound");
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            return View(companyViewModel);
        }

        // GET: Companies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return View("NotFound");
            }

            var company = await _compmaniesServices.GetById(id);

            if (company == null)
            {
                return View("NotFound");
            }

            return View(company);
        }

        // POST: Companies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            if (id == null)
            {
                return View("NotFound");
            }

            var result = await _compmaniesServices.Delete(id);

            if (result == false)
            {
                return View("NotFound");
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

CRM.Web/Controllers/ContactsController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CRM.Web.Models.Entities;
using CRM.Web.Models.ViewModels;
using CRM.Web.Services;
using CRM.Web.Data;

namespace CRM.Web.Controllers
{
    public class ContactsController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IContactsService _contactsService;

        public ContactsController(AppDbContext context, IContactsService contactsService)
        {
            _context = context;
            _contactsService = contactsService;
        }

        // GET: Contacts
        public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter, int? pageNumber)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["FirstNameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "first_name_desc" : "";
            ViewData["LastNameSortParm"] = sortOrder == "LastName" ? "last_name_desc" : "LastName";
            ViewData["PhoneSortParm"] = sortOrder == "Phone" ? "phone_desc" : "Phone";
            ViewData["EmailSortParm"] = sortOrder == "Email" ? "email_desc" : "Email";
            ViewData["CompanySortParm"] = sortOrder == "Company" ? "company_desc" : "Company";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            var contacts = await _contactsService.GetPaginatedList(sortOrder, searchString, currentFilter, pageNumber);

            return View(contacts);
        }

        // GET: Contacts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return View("NotFound");
            }

            var contact = await _contactsService.GetById(id);

            if (contact == null)
            {
                return View("NotFound");
            }

            var contactViewModel = new DetailsContactViewModel
            {
                Activities = contact.Activities,
                Company = contact.Company,
                Contact = contact
            };

            return View(contactViewModel);
        }

        // GET: Contacts/Create
        public IActionResult Create()
        {
            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Name");

            return View();
        }

        // POST: Contacts/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FirstName,LastName,Position,Description,Source,Phone,Email,CompanyId,Id,CreatedDate,UpdatedDate")] FormContactViewModel contactViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            Contact contact = new Contact 
            {
                FirstName = contactViewModel.FirstName,
                LastName = contactViewModel.LastName,
                Position = contactViewModel.Position,
                Description = contactViewModel.Description,
                Source = (Contact.Sources)contactViewModel.Source,
                Phone = contactViewModel.Phone,
                Email = contactViewModel.Email,
                CompanyId = contactViewModel.CompanyId
            };

            var successful = await _contactsService.Create(contact);

            if (!successful)
            {
                return View("NotFound");
            }

            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Name", contact.CompanyId);

            return RedirectToAction(nameof(Index));
        }

        // GET: Contacts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return View("NotFound");
            }

            var contact = await _contactsService.GetById(id);
            
            if (contact == null)
            {
                return View("NotFound");
            }

            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Name", contact.CompanyId);

            FormContactViewModel contactViewModel = new FormContactViewModel
            {
                Id = contact.Id,
                FirstName = contact.FirstName,
                LastName = contact.LastName,
                Position = contact.Position,
                Description = contact.Description,
                Source = (FormContactViewModel.Sources)contact.Source,
                Phone = contact.Phone,
                Email = contact.Email,
                CompanyId = contact.CompanyId,
                CreatedDate = contact.CreatedDate,
                UpdatedDate = contact.UpdatedDate
            };

            return View(contactViewModel);
        }

        // POST: Contacts/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FirstName,LastName,Position,Description,Source,Phone,Email,CompanyId,Id,CreatedDate,UpdatedDate")] FormContactViewModel contactViewModel)
        {
            if (id != contactViewModel.Id)
            {
                return View("NotFound");
            }

            Contact contact = new Contact
            {
                Id = contactViewModel.Id,
                FirstName = contactViewModel.FirstName,
                LastName = contactViewModel.LastName,
                Position = contactViewModel.Position,
                Description = contactViewModel.Description,
                Source = (Contact.Sources)contactViewModel.Source,
                Phone = contactViewModel.Phone,
                Email = contactViewModel.Email,
                CompanyId = contactViewModel.CompanyId,
                CreatedDate = contactViewModel.CreatedDate,
                UpdatedDate = contactViewModel.UpdatedDate
            };

            if (ModelState.IsValid)
            {
                try
                {
                    var result = await _contactsService.Update(contact);

                    if (result == false)
                    {
                        return View("NotFound");
                    }

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!(await _contactsService.Exists(contact.Id)))
                    {
                        return View("NotFound");
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Name", contact.CompanyId);
            
            return View(contactViewModel);
        }

        // GET: Contacts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return View("NotFound");
            }

            var contact = await _contactsService.GetById(id);

            if (contact == null)
            {
                return View("NotFound");
            }

            return View(contact);
        }

        // POST: Contacts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            if (id == null)
            {
                return View("NotFound");
            }

            var result = await _contactsService.Delete(id);

            if (result == false)
            {
                return View("NotFound");
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

CRM.Web/Views/Contacts/Create.cshtml
@model FormContactViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Создать новый контакт</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label">Имя</label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label">Фамилия</label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Source" class="control-label">Источник</label>
                <select asp-for="Source" class="form-control" asp-items="Html.GetEnumSelectList<FormContactViewModel.Sources>()">
                    <option selected="selected" value="">---Выберите, пожалуйста---</option>
                </select>
                <span asp-validation-for="Source" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label">Номер мобильного телефона</label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label">Email</label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CompanyId" class="control-label">Компания</label>
                <select asp-for="CompanyId" class="form-control" asp-items="ViewBag.CompanyId">
                    <option selected="selected" value="">---Выберите, пожалуйста---</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Position" class="control-label">Позиция</label>
                <input asp-for="Position" class="form-control" />
                <span asp-validation-for="Position" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Описание</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Создать" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CRM.Web/Views/Contacts/Delete.cshtml
@model Contact

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Вы уверены, что хотите удалить @Html.DisplayFor(model => model.FirstName) @Html.DisplayFor(model => model.LastName)?</h3>
<div>
    <hr />
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Да (Удалить)" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-success">Нет (Назад)</a>
    </form>
</div>

CRM.Web/Views/Contacts/Details.cshtml
@model DetailsContactViewModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <div class="button-panel">
        <h3>@Html.DisplayFor(model => model.Contact.FirstName) @Html.DisplayFor(model => model.Contact.LastName)</h3>
        <p>
            <a asp-action="Edit" asp-route-id="@Model.Contact.Id" class="btn btn-primary btn-sm">Редактировать</a>
        </p>
        <p>
            <a asp-action="Create" class="btn btn-primary btn-sm">Создать</a>
        </p>
        <p>
            <a asp-action="Delete" asp-route-id="@Model.Contact.Id" class="btn btn-primary btn-sm">Удалить</a>
        </p>
    </div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Имя
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Contact.FirstName)
        </dd>
        <dt class="col-sm-2">
            Фамилия
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Contact.LastName)
        </dd>
        <dt class="col-sm-2">
            Номер мобильного телефона
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Contact.Phone)
        </dd>
        <dt class="col-sm-2">
            Email
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Contact.Email)
        </dd>
        <dt class="col-sm-2">
            Источник
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Contact.Source)
        </dd>
        <dt class="col-sm-2">
            Компания
        </dt>
        <dd class="col-sm-10">
            <a asp-controller="Companies" asp-action="Details" asp-route-id="@Model.Company.Id">
                @Html.DisplayFor(model => model.Company.Name)
            </a>
        </dd>
        <dt class="col-sm-2">
            Позиция
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Contact.Position)
        </dd>
        <dt class="col-sm-2">
            Описание
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Contact.Description)
        </dd>
        <dt class="col-sm-2">
            Дата регистрации
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Contact.CreatedDate)
        </dd>
        <dt class="col-sm-2">
            Дата обновления
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Contact.UpdatedDate)
        </dd>
    </dl>
</div>
<div>
    <h4>Сопутствующая деятельность</h4>
    <div>
        <p>
            <a asp-controller="Activities" asp-action="Create" class="btn btn-primary btn-sm">Добавить</a>
        </p>
    </div>
    <hr />
    <table class="table">
        <thead>
            <tr>
                <th>
                    <a>Название</a>
                </th>
                <th>
                    <a>Тип</a>
                </th>
                <th>
                    <a>Дата начала</a>
                </th>
                <th>
                    <a>Дата окончания</a>
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Activities)
            {
                <tr onclick="location.href = '@(Url.Action("Details", "Activities", new { id = item.Id }))'">
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Type)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.StartDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EndDate)
                    </td>
                    <td>
                        <a asp-controller="Activities" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-default">Редактировать</a> |
                        <a asp-controller="Activities" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-default">Удалить</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

CRM.Web/Views/Contacts/Edit.cshtml
@model FormContactViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Edit Contact</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label">Имя</label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label">Фамилия</label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Source" class="control-label">Источник</label>
                <select asp-for="Source" class="form-control" asp-items="Html.GetEnumSelectList<FormContactViewModel.Sources>()">
                    <option selected="selected" value="">---Выберите, пожалуйста---</option>
                </select>
                <span asp-validation-for="Source" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label">Номер мобильного телефона</label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label">Email</label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CompanyId" class="control-label">Компания</label>
                <select asp-for="CompanyId" class="form-control" asp-items="ViewBag.CompanyId">
                    <option selected="selected" value="">---Please select---</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Position" class="control-label">Позиция</label>
                <input asp-for="Position" class="form-control" />
                <span asp-validation-for="Position" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Описание</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="CreatedDate" />
            <input type="hidden" asp-for="UpdatedDate" />
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CRM.Web/Views/Contacts/Index.cshtml
@model PaginatedList<Contact>

@{
    Layout = "~/Views/Shared/_ListViewLayout.cshtml";
}

<table class="table">
    <thead>
        <tr>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["FirstNameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Имя</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["LastNameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Фамилия</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["PhoneSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Номер мобильного телефона</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["EmailSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Email</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["CompanySortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Компания</a>
            </th>
            <th>Действия</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr onclick="location.href = '@(Url.Action("Details", "Contacts", new { id = item.Id }))'">
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Phone)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Company.Name)
                </td>
                <td>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-default">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>